name: flood_reporting_app
description: A multi-platform flood reporting application with a step-by-step wizard interface.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^2.32.0
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  geolocator: ^12.0.0
  geocoding: ^2.1.0
  image_picker: ^1.1.2
  uuid: ^3.0.7
  google_fonts: ^5.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/

