// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF-7iP2WsgMfkKTC0IzQKQtThl-OQzsgE',
    appId: '1:401161227075:web:0eb767adcdcf32c684bdf6',
    messagingSenderId: '401161227075',
    projectId: 'flood-alert-ced47',
    authDomain: 'flood-alert-ced47.firebaseapp.com',
    storageBucket: 'flood-alert-ced47.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAiSqEDZg-gnaynHmWdwoSmCU6FZgtIs8',
    appId: '1:401161227075:android:95df0dfe131683cd84bdf6',
    messagingSenderId: '401161227075',
    projectId: 'flood-alert-ced47',
    storageBucket: 'flood-alert-ced47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcT0RLba9iRWk_xSiN6vXx6kCkXxOTTFE',
    appId: '1:401161227075:ios:76bff372b2c01c6184bdf6',
    messagingSenderId: '401161227075',
    projectId: 'flood-alert-ced47',
    storageBucket: 'flood-alert-ced47.firebasestorage.app',
    iosBundleId: 'com.example.floodReportingApp',
  );
}
